### ISSUE TITLE
Passera i386 (32 bit) Windows generates 12-character default

### ISSUE THREAD

**Issue by Zipgit** [mwgg/passera#16]
Just upgraded an old notebook which runs 32-bit Win7 Pro, and installed Passera. 

The default is supposed to generate a code word of 16 characters w/ special characters.

As installed, my 32-bit Passera generates 12-character only. 

Unlike the Firefox app (which no longer works in FFox Quantum), there seems to be no easy way for a user to change the settings through the CMD window.

**Comment by mwgg** [comment]
Windows 32-bit binaries do generate bad results, for reasons unknown, this is listed under "Known Issues". 
Since the recent add-on API changes in Firefox, every developer had to update their add-on with the new API which is a significant undertaking. I am largely absent from this project and unfortunately have no time to work on it, and anyone is more than welcome to continue this work.
